services:

  segmentation:
    container_name: cell_nuclei
    build: .
    runtime: nvidia
    volumes:
      - type: bind
        source: .
        target: /app
    user: 1000:1000
    working_dir: /app

