name: 'Run pytest'

on: [pull_request]

jobs:
  test-pipelines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry config virtualenvs.create false --local
          poetry install --with test,lint,dev

      - name: Test with pytest
        run: |
          pytest
